# Generated by Django 2.1 on 2021-03-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(help_text='Enter a name for your contact', max_length=100)),
                ('profile_picture', models.ImageField(upload_to='contacts/images')),
            ],
        ),
    ]
