# Generated by Django 2.1 on 2021-03-11 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20210311_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='files',
        ),
        migrations.AddField(
            model_name='email',
            name='sent_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='emails', to='contacts.File'),
        ),
    ]
