# Generated by Django 2.1 on 2021-03-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20210311_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='contacts/images'),
        ),
    ]
