# Generated by Django 2.1 on 2021-03-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_contact_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
