# Generated by Django 2.1 on 2021-03-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_auto_20210314_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
