# Generated by Django 2.1 on 2021-03-14 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0011_email_is_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='emails', to=settings.AUTH_USER_MODEL),
        ),
    ]
