# Generated by Django 2.1 on 2021-03-14 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0012_email_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='receiver',
            new_name='receivers',
        ),
    ]
