# Generated by Django 2.1 on 2021-03-14 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0014_auto_20210314_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='is_selected',
        ),
    ]
