# Generated by Django 2.1 on 2021-03-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0015_remove_email_is_selected'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'ordering': ['date_created']},
        ),
        migrations.AddField(
            model_name='email',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='email',
            name='subject',
            field=models.CharField(max_length=250),
        ),
    ]
