# Generated by Django 2.1 on 2021-03-31 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0017_remove_contact_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='email',
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
